import outlineData from '@/data/outline.json';

/**
 * The 2024 ISC2 outline, flattened to `id -> title` at both the task and the
 * subtask level, because the bank's `outlineItems` use both.
 *
 * Generated by scripts/sync-outline.mjs from content-pipeline. Do not hand-edit.
 */
interface OutlineData {
    source: string;
    counts: Record<string, number>;
    domainOf: Record<string, string>;
    items: Record<string, string>;
}

const data = outlineData as OutlineData;

/** "Understand and apply security concepts", or undefined for an unknown id. */
export const objectiveTitle = (id: string): string | undefined => data.items[id];

/** The domain an objective belongs to, e.g. "1.3.2" -> "domain_1". */
export const objectiveDomain = (id: string): string | undefined => data.domainOf[id];

/** Every objective id the outline defines, tasks and subtasks alike. */
export const OBJECTIVE_IDS: string[] = Object.keys(data.items);

/** How many objectives the outline defines for a domain. Denominator for coverage. */
export const objectivesInDomain = (domainId: string): number =>
    Object.values(data.domainOf).filter(d => d === domainId).length;

export const outlineSource = (): string => data.source;
